### ISSUE TITLE
Text disappears if you edit file, open another file, and switch back to original file

### ISSUE THREAD

**Issue by bigcfk** [dtjm/textdropapp.com#38]
I was typing in todo.txt and clicked to another document to copy & paste from. Copied it, and when I clicked back to todo.txt it was blank. Went to dropbox, restored a version from 51 seconds ago, and it was all there. Go back to TextDrop, open todo.txt, copy in the text I wanted. Then tried clicking  on another document, went back and todo.txt was deleted again. I opened a different document and clicked over to another one, and this doesn't happen.

gist: open document, click to another document, first document's text disappears – but only sometimes (?)

**Comment by dtjm** [comment]
What browser and OS are you on?

**Comment by dtjm** [comment]
Confirmed. This happens if you edit a file, go to another file, then come back to it.

**Comment by dtjm** [comment]
Note to self: fix in models.js line 70.  Directory contents are being refreshed in the middle of a save operation, deleting the contents because it looks like the rev has changed. Only delete data if model is in NEW, CLEAN or FETCHING state, not if it is DIRTY or SAVING. If it is FETCHING, then probably should re-fetch.

**Comment by dtjm** [comment]
fixed
