### ISSUE TITLE
Typing File URL

### ISSUE THREAD

**Issue by bigcfk** [dtjm/textdropapp.com#63]
Hey, so I dabbled in typing out a file's url
[ https://textdrop-beta.herokuapp.com/dropbox/Text/btv.txt ]
1. I typed /text/ instead of /Text/ and received a "file not found" notice. 
   Which makes total sense, but can capitalization be ignored?
2. To type "textdrop-beta.herokuapp.com/dropbox/etc…" or "textdropapp.com/dropbox/folder/example.txt" is somewhat of a fingerful. It'd be much easier to type a smaller site name then the file location. Could a shorter URL be acquired? txtdrp.com perhaps? or something with a sweet domain, like .in ?

**Comment by dtjm** [comment]
#1 I don't think would be possible because I would still have to guess the file name on the server, and there would be a lot of different combinations to guess. 

#2 I would be open to it if you found a sweet domain that was open and affordable, but short URLs is honestly not a high priority for me.  However you might be able to hack it by editing your hosts file if you _really_ wanted shorter URLs, or even buying your own domain and just redirecting to textdrop.
